#!/usr/bin/python3
# Helper script for automatic 'pmcyg' updating
# RW Penney, May 2011

from pmcyg import PMbuilder, ProcessPackageFiles


PKG_HOST = 'http://www.mirrorservice.org/sites/sourceware.org/pub/cygwin'
PKG_LISTS = [ 'example.pkgs' ]

builder = PMbuilder(MirrorSite=PKG_HOST,
                    BuildDirectory='./cygwin',
                    AllPackages=False,
                    IncludeSources=False,
                    RemoveOutdated='ask',
                    ISOfilename='./cygwin-pmcyg.iso',
                    DummyDownload=False)

ProcessPackageFiles(builder, PKG_LISTS)
